[package]
name = "lazystream"
version = "1.9.2"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
stats-api = { git = "https://github.com/tarkah/stats-api", rev = "1d8f53d940a5cee741a8e5b744ec4e5573b835fb" }

failure = "0.1"
chrono = "0.4"
read_input = "0.8"
structopt = "0.3"
colored = "1.9"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

futures = "0.3.1"
async-std = { version = "1.0", features = ['unstable'] }

http = "0.1"
curl = { version = "0.4", default-features=false, features = ["static-curl", "static-ssl", "http2"] }
http-client = { version = "1.1.1", features = ["native_client"] }
mdns = "0.3.1"