[package]
name = "lazystream"
version = "1.7.1"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
stats-api = { git = "https://github.com/tarkah/stats-api", rev = "f8058c366366c23457819a4a05d34ad61ae26bcd" }

failure = "0.1"
chrono = "0.4"
read_input = "0.8"
structopt = "0.3"
colored = "1.9"

futures = "0.3.1"
async-std = { version = "1.0", features = ['unstable'] }

http = "0.1"
curl = { version = "0.4", default-features=false, features = ["static-curl", "static-ssl", "http2"] }
http-client = { version = "1.1.1", features = ["native_client"] }
mdns = "0.3.1"